name: Semaphore UI
version: 0.9.20
slug: ansible_semaphore
description: Modern UI for Ansible, Terraform/OpenTofu/Terragrunt, PowerShell and other DevOps tools.
startup: services
boot: auto
ingress: true
ingress_port: 3100
ingress_stream: true
ports:
  3100/tcp: 3100
ports_description:
  3100/tcp: Web interface
panel_icon: mdi:ansible
arch:
  - amd64
  - aarch64
map:
  - data:rw
  - ssl:ro
options:
  SEMAPHORE_ADMIN: admin
  SEMAPHORE_ADMIN_PASSWORD: changeme
  SEMAPHORE_ADMIN_NAME: HA-Admin
  SEMAPHORE_ADMIN_EMAIL: admin@example.com
schema:
  SEMAPHORE_ADMIN: str
  SEMAPHORE_ADMIN_PASSWORD: password
  SEMAPHORE_ADMIN_NAME: str
  SEMAPHORE_ADMIN_EMAIL: email
stable: experimental
